version: '3'

services:

  ngrok:
    container_name: ngrok_tunnel
    image: wernight/ngrok
    ports:
      - "4040:4040"
    links:
      - python
    environment:
      - NGROK_AUTH=3fVv5QDD6Wh5jDUg7CtEg_6tsUV7Nz5gy1M6vZA7myF
      - NGROK_PORT=python:5000
      - NGROK_PROTOCOL=http

  python:
    container_name: python_app_server
    build: app/.
    ports:
      - "5000:5000"
    volumes:
      - "./app:/app"
    restart: always

  # spark:
  #   container_name: spart_chatbot
  #   build: spark/.
  #   ports:
  #     - "5001:4040"
  #     - "5002:5000"
  #   volumes:
  #     - ./spark/hello_bot:/workspace
  #     - ./spark/helpers:/workspace/helpers
  #     - ./spark/config:/opt/config0
  #   environment:
  #     - PYTHONPATH=/workspace/
  #   entrypoint: /workspace/run.sh
  #   restart: always
